language: node_js
node_js: stable
cache: bundler
gemfile: docs/Gemfile
script:
  - npm run build
  - bundle exec jekyll algolia --source docs --destination docs/_site --config docs/_config.yml
deploy:
  provider: pages
  skip-cleanup: true
  github_token: $GIT_TOKEN
  keep-history: true
  local-dir: dist
  on:
    branch: master
rvm:
  - 2.4